language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

sudo: false

addons:
  apt:
    packages:
      - ctags

install:

before_script:
  - travis_retry composer self-update
  - travis_retry composer require satooshi/php-coveralls:dev-master --no-update --dev
  - travis_retry composer install
  - phpenv rehash
  - cd vendor/bin/ && curl -LO https://github.com/phpbrew/Onion/raw/master/onion && chmod +x onion && cd -
  - export PATH=$PATH:$PWD/vendor/bin/
  - mkdir -p -v .phpbrew/build
  - mkdir -p -v .phpbrew/distfiles
  - mkdir -p -v .phpbrew/register
  - mkdir -p -v .phpbrew/php
  - cp -v shell/bashrc .phpbrew/
  - source shell/bashrc

script:
  - source shell/bashrc
  # - ./scripts/compile && phpunit --bootstrap tests/bootstrap-phar.php # test phar
  - phpunit --debug

after_script:
  - php vendor/bin/coveralls

cache:
  apt: true
  directories:
    - vendor
    - .phpbrew/distfiles
    - .phpbrew/php
