language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - phpenv rehash
  - curl http://install.onionphp.org/ | bash
  - curl -O https://raw.github.com/c9s/Onion/master/onion
  - composer install --dev

script:
  - source phpbrew.sh
  - ./scripts/compile && phpunit --bootstrap tests/bootstrap-phar.php # test phar
  - phpunit --debug # test src
