language: php
php:
  - 5.3
  - 5.4

before_script:
  - phpenv rehash
  - curl http://install.onionphp.org/ | bash
  - curl -O https://raw.github.com/c9s/Onion/master/onion
  - php onion install
#    - pear channel-discover pear.corneltek.com
#    - pear install -f -a corneltek/PHPUnit_TestMore
#    - pear install -f -a corneltek/Universal
#    - pear install -f -a corneltek/PEARX

script: phpunit --debug
